// County Choropleth Series template -- whisker-tokenized Typst, rendered
// by onepagr::render_onepager(). All placeholder tokens map to named
// elements in the calling script's `data` list.
//
// SHAPE: unlike cohort_summary (contrasts two groups) or trend_snapshot
// (tracks one metric over time), this template's informational shape is a
// GEOGRAPHIC bivariate comparison -- one headline choropleth map (an
// outcome variable vs. a composite index) on the front, plus the
// composite index's individual component maps on the back, each with an
// interpretive caption. Generalized from the KY SVI x drug-overdose
// linkage analysis; the map images themselves (5 pre-rendered PNGs, one
// bivariate choropleth each, built with the biscale/ggplot2/cowplot R
// stack) are supplied by the calling script, not generated by Typst --
// this template only lays them out with real alt text and captions.
//
// THEME/COMPONENT ARCHITECTURE: same pattern as every other onepagr
// template -- theme.typ/components.typ are staged in next to this file at
// compile time by render_onepager()/export_template(), so nothing here
// needs to change to re-skin. See cohort_summary/template.typ's header
// comment for the full rationale (lexical-scoping bug this avoids).
#import "theme.typ": theme, theme-grad
#import "components.typ": *

// Route contact_email through a variable rather than splicing
// {{{contact_email}}} directly into markup body wherever it's displayed.
// Typst's markup parser treats a bare "@" as the start of label-reference
// syntax (e.g. "kiprc@uky.edu" parses as "kiprc" + a reference to label
// <uky.edu>, failing to compile with "label <uky.edu> does not exist") --
// confirmed directly, not assumed. Escaping it as "\@" only fixes that
// for a token substituted straight into markup SOURCE text; substituted
// into a quoted Typst STRING argument instead (as page-footer's own
// contact-email parameter is), "\@" is not a recognized string escape and
// the literal backslash character renders in the output. Interpolating a
// plain (unescaped) string value via #variable-name, as done below and in
// page-footer, sidesteps this entirely -- Typst never re-parses an
// already-evaluated string's characters for markup syntax, so the "@" is
// inert either way. Keep contact_email UNESCAPED in the R-side data.
#let contact-email = "{{{contact_email}}}"

#let footer = page-footer(
  theme, theme-grad,
  "assets/partner-org-a-white.png", "Partner Organization A logo",
  "assets/primary-org-white.png", "Primary Organization logo",
  "assets/partner-org-b-white.png", "Partner Organization B logo",
  "{{{org_full}}}", "{{{contact_url}}}", "{{{contact_email}}}",
)

#apply-base-styles([{{{doc_title}}}], "{{{org_full}}}", theme, footer)[

// ============================================================
// HEADER
// ============================================================
#block(width: 100%, fill: theme-grad.brand-blue-grad, clip: true, inset: (x: 20pt, y: 10pt), above: 0pt, below: 0pt)[
  #place(top + right, dx: 40pt, dy: -30pt)[
    #pdf.artifact(kind: "background")[#image("assets/header-texture.png", width: 260pt)]
  ]
  #grid(columns: (auto, 1fr), column-gutter: 14pt, align: horizon,
    image("assets/primary-org-white.png", height: 28pt, alt: "Primary Organization logo"),
    [
      #text(fill: white, size: 12pt, weight: "bold")[{{{doc_title}}}] \
      #text(fill: white.transparentize(15%), size: 9pt)[{{{doc_subtitle}}}]
    ]
  )
]
#block(fill: theme.brand-midnight, inset: (x: 20pt, y: 6pt), width: 100%, above: 0pt)[
  #text(fill: white, size: 8pt)[
    *DATA* {{{strip_data}}}  #h(1.5em)
    *PERIOD* {{{strip_period}}}  #h(1.5em)
    *DESIGN* {{{strip_design}}}  #h(1.5em)
    *GEOGRAPHY* {{{strip_geography}}}
  ]
]

#pad(x: theme.content-pad-x)[
#v(theme.space-md)

// ============================================================
// AT A GLANCE
// ============================================================
= {{{strip_geography}}} AT A GLANCE #sym.dash.en {{{strip_period}}}
#v(theme.space-sm)

#block(breakable: false)[
  #grid(
    columns: (1fr, 1fr, 1fr), column-gutter: 6pt,
    fill: theme-grad.card-bg-grad, inset: 6pt,
    stroke: (x, ..) => (top: theme.stroke-accent + (theme.brand-blue, theme.brand-accent, theme.brand-midnight).at(x), rest: theme.stroke-border + theme.box-border),
    stat-card(theme, [{{{n_statewide_od_deaths}}}], [Resident drug overdose deaths, {{{strip_period}}}]),
    stat-card(theme, [{{{statewide_od_rate}}}], [Statewide crude death rate, per 100,000 residents], color: theme.brand-accent),
    stat-card(theme, [{{{n_high_svi_counties}}}], [Counties in the highest Social Vulnerability Index tertile], color: theme.brand-midnight),
  )
]

// ============================================================
// HEADLINE MAP: SVI vs. OVERDOSE DEATH RATE
// ============================================================
#v(theme.space-md)
= SOCIAL VULNERABILITY AND OVERDOSE DEATH RATES, BY COUNTY
#v(theme.space-sm)

// Front-page real estate: the headline map is this page's dominant
// visual, so it gets most of the column width (75%) rather than an even
// split with the explainer text -- a narrow map rendered small would
// waste most of the page's vertical space below it (confirmed directly:
// an even 58/42 split left roughly two-thirds of the page blank beneath
// a map rendered too small to use the available height).
#grid(columns: (75fr, 25fr), column-gutter: 12pt,
  [
    #figure(
      box(stroke: 1pt + black, width: 100%)[#image("{{{map0_path}}}", width: 100%)],
      alt: "Kentucky county map. Each county is shaded by a 3-by-3 bivariate color grid combining its overall Social Vulnerability Index tertile with its crude drug overdose death rate tertile. Dark green marks counties in the highest tertile for both measures; light gray marks counties in the lowest tertile for both.",
    )
  ],
  [
    #text-box(theme, theme-grad, [HOW TO READ THIS MAP])[
      Each county is shaded by two ranks at once: Social Vulnerability Index (SVI, left #sym.arrow.r right) and overdose death rate (bottom #sym.arrow.r top), each split into thirds across all 120 counties.
      #v(theme.space-xs)
      *Dark green* #sym.dash.en top third on #emph[both]. *Orange* #sym.dash.en high death rate, lower SVI. *Blue-gray* #sym.dash.en high SVI, lower death rate. *Light gray* #sym.dash.en low on both.
      #v(theme.space-xs)
      Shows where the two measures co-occur geographically -- not that one causes the other.
    ]
  ]
)

#v(theme.space-xs)
#text(size: 7pt, fill: theme.text-muted)[SVI is CDC/ATSDR's composite Social Vulnerability Index (sum of all four theme rankings), {{{data_vintage}}}. Overdose deaths are Kentucky resident deaths with an underlying cause of death consistent with the standard CDC/NCHS drug-poisoning definition (ICD-10 X40#sym.dash.en 44, X60#sym.dash.en 64, X85, Y10#sym.dash.en 14), {{{strip_period}}}, crude rate per 100,000 residents (not age-adjusted).]

] // close page-1 body
#pagebreak()
#pad(x: theme.content-pad-x)[
#v(theme.space-sm)

// ============================================================
// COMPONENT FACTORS (page 2)
// ============================================================
= COMPONENT FACTORS BEHIND THE SVI SCORE
#v(theme.space-xs)
#text(size: 7.5pt, fill: theme.text-secondary)[The composite SVI score above is built from many measures. The four maps below isolate individual components most directly tied to health-care access and economic strain, each paired with the same overdose death rate as the headline map -- so a reader can see which specific factor is driving a county's vulnerability, not just that it's vulnerable overall.]
#v(theme.space-sm)

#grid(columns: (1fr, 1fr), column-gutter: 10pt, row-gutter: 8pt,
  [
    #figure(
      box(stroke: 1pt + black, width: 100%)[#image("{{{map1_path}}}", width: 100%)],
      alt: "Kentucky county map, bivariate choropleth of unemployment rate against overdose death rate, using the same 3-by-3 color grid as the headline map.",
    )
    #text(size: 7.5pt, fill: theme.text-secondary)[*{{{map_title1}}}.* Counties where joblessness is common; unemployment strains household finances and can reduce access to treatment and stable housing.]
  ],
  [
    #figure(
      box(stroke: 1pt + black, width: 100%)[#image("{{{map2_path}}}", width: 100%)],
      alt: "Kentucky county map, bivariate choropleth of the percentage of the population without health insurance against overdose death rate, using the same 3-by-3 color grid as the headline map.",
    )
    #text(size: 7.5pt, fill: theme.text-secondary)[*{{{map_title2}}}.* Uninsured residents face direct financial barriers to substance use treatment, medication-assisted treatment, and routine care that can catch a problem earlier.]
  ],
  [
    #figure(
      box(stroke: 1pt + black, width: 100%)[#image("{{{map3_path}}}", width: 100%)],
      alt: "Kentucky county map, bivariate choropleth of the percentage of persons below 150 percent of the poverty line against overdose death rate, using the same 3-by-3 color grid as the headline map.",
    )
    #text(size: 7.5pt, fill: theme.text-secondary)[*{{{map_title3}}}.* Poverty limits access to transportation, treatment, and other resources that support recovery and reduce overdose risk.]
  ],
  [
    #figure(
      box(stroke: 1pt + black, width: 100%)[#image("{{{map4_path}}}", width: 100%)],
      alt: "Kentucky county map, bivariate choropleth of the percentage of housing units that are cost-burdened against overdose death rate, using the same 3-by-3 color grid as the headline map.",
    )
    #text(size: 7.5pt, fill: theme.text-secondary)[*{{{map_title4}}}.* Housing cost burden (30%+ of income spent on housing) reflects material hardship and displacement risk, both linked to worse health outcomes.]
  ],
)

#v(theme.space-sm)
#rect(fill: theme-grad.disclaimer-bg-grad, stroke: (left: theme.stroke-accent-left + theme.disclaimer-border, rest: theme.stroke-border + theme.box-border), radius: theme.radius-card, inset: 5pt, width: 100%)[
  // Same pattern used by every other onepagr template's DISCLAIMER box --
  // a locally-scoped `show heading: set text(...)` styling rule (not a
  // content-replacing rule) keeps `== DISCLAIMER` tagged as a real
  // heading in the PDF's structure tree rather than an ordinary paragraph
  // that merely looks bold. See components.typ's apply-base-styles
  // comment for why this distinction matters for PDF/UA conformance.
  #show heading: set text(size: 8pt, weight: "bold", fill: theme.disclaimer-text, tracking: 0.5pt)
  == DISCLAIMER
  #v(theme.space-xs)
  #text(size: 8pt, fill: theme.disclaimer-text)[{{{disclaimer_text}}}]
]

#v(theme.space-xs)
#text(size: 7pt, fill: theme.text-muted)[*Data sources:* {{{footnote_sources}}} #h(0.5em)|#h(0.5em) *Period:* {{{strip_period}}} #h(0.5em)|#h(0.5em) *Contact:* {{{org_full}}} at #link("mailto:" + contact-email)[#contact-email]]
] // close body #pad(x: theme.content-pad-x)

] // close #apply-base-styles body
