// County Choropleth Series template -- whisker-tokenized Typst, rendered
// by onepagr::render_onepager(). All placeholder tokens map to named
// elements in the calling script's `data` list.
//
// SHAPE: unlike cohort_summary (contrasts two groups) or trend_snapshot
// (tracks one metric over time), this template's informational shape is a
// GEOGRAPHIC bivariate comparison -- one headline choropleth map (an
// outcome variable vs. a composite index) on the front, plus the
// composite index's individual component maps on the back, each with an
// interpretive caption. Generalized from the KY SVI x drug-overdose
// linkage analysis; the map images themselves (5 pre-rendered PNGs, one
// bivariate choropleth each, built with the biscale/ggplot2/cowplot R
// stack) are supplied by the calling script, not generated by Typst --
// this template only lays them out with real alt text and captions.
//
// THEME/COMPONENT ARCHITECTURE: same pattern as every other onepagr
// template -- theme.typ/components.typ are staged in next to this file at
// compile time by render_onepager()/export_template(), so nothing here
// needs to change to re-skin. See cohort_summary/template.typ's header
// comment for the full rationale (lexical-scoping bug this avoids).
#import "theme.typ": theme, theme-grad
#import "components.typ": *

// Route contact_email through a variable rather than splicing
// {{{contact_email}}} directly into markup body wherever it's displayed.
// Typst's markup parser treats a bare "@" as the start of label-reference
// syntax (e.g. "kiprc@uky.edu" parses as "kiprc" + a reference to label
// <uky.edu>, failing to compile with "label <uky.edu> does not exist") --
// confirmed directly, not assumed. Escaping it as "\@" only fixes that
// for a token substituted straight into markup SOURCE text; substituted
// into a quoted Typst STRING argument instead (as page-footer's own
// contact-email parameter is), "\@" is not a recognized string escape and
// the literal backslash character renders in the output. Interpolating a
// plain (unescaped) string value via #variable-name, as done below and in
// page-footer, sidesteps this entirely -- Typst never re-parses an
// already-evaluated string's characters for markup syntax, so the "@" is
// inert either way. Keep contact_email UNESCAPED in the R-side data.
#let contact-email = "{{{contact_email}}}"

// Logo paths/alt-text and the header texture are tokens, not hardcoded
// literals -- see cohort_summary/template.typ's identical comment for
// why. Also fixed here: the last argument now uses the contact-email
// variable (defined above) instead of the raw {{{contact_email}}} token
// directly -- consistent with why that variable exists at all (see this
// file's header comment on contact-email), even though passing the raw
// token here was never actually broken given this template's fixture
// already supplies an unescaped value.
// strip-links: false because this template self-places the footer as
// real body content, not page(footer:) furniture -- see this call's
// counterpart comment below the #apply-base-styles() call, and
// page-footer()'s own comment in components.typ, for why leaving this
// at the default (true) would be a real, PAC-confirmed accessibility
// bug here (contact-url/contact-email rendering as inert, unlinked text
// with no actual reason to be inert anymore).
#let footer = page-footer(
  theme, theme-grad,
  "{{{logo_partner_a_path}}}", "{{{logo_partner_a_alt}}}", "{{{show_partner_a}}}",
  "{{{logo_primary_path}}}", "{{{logo_primary_alt}}}",
  "{{{logo_partner_b_path}}}", "{{{logo_partner_b_alt}}}", "{{{show_partner_b}}}",
  "{{{org_full}}}", "{{{contact_url}}}", contact-email,
  strip-links: false,
)

// footer is placed explicitly per page below (#place(bottom + center)),
// NOT passed here -- see apply-base-styles()'s own comment in
// components.typ for why: page(footer:) content is unconditionally
// excluded from the PDF's accessibility tree, alt text or not, so a
// template with a known fixed page count self-places the footer as real
// body content instead.
#apply-base-styles([{{{doc_title}}}], "{{{org_full}}}", theme, margin-bottom: 0.056in)[

// ============================================================
// HEADER
// ============================================================
#block(width: 100%, fill: theme-grad.brand-blue-grad, clip: true, inset: (x: 20pt, y: 10pt), above: 0pt, below: 0pt)[
  #place(top + right, dx: 40pt, dy: -30pt)[
    #pdf.artifact(kind: "background")[#image("{{{header_texture_path}}}", width: 260pt)]
  ]
  #grid(columns: (auto, 1fr), column-gutter: 14pt, align: horizon,
    image("{{{logo_primary_path}}}", height: 28pt, alt: "{{{logo_primary_alt}}}"),
    [
      #text(fill: white, size: 12pt, weight: "bold")[{{{doc_title}}}] \
      #text(fill: white.transparentize(15%), size: 9pt)[{{{doc_subtitle}}}]
    ]
  )
]
#block(fill: theme.brand-midnight, inset: (x: 20pt, y: 6pt), width: 100%, above: 0pt)[
  #text(fill: white, size: 8pt)[
    *DATA* {{{strip_data}}}  #h(1.5em)
    *PERIOD* {{{strip_period}}}  #h(1.5em)
    *DESIGN* {{{strip_design}}}  #h(1.5em)
    *GEOGRAPHY* {{{strip_geography}}}
  ]
]

#pad(x: theme.content-pad-x)[
#v(theme.space-md)

// ============================================================
// AT A GLANCE
// ============================================================
= {{{strip_geography}}} at a Glance - {{{strip_period}}}
#v(theme.space-sm)

#block(breakable: false)[
  #grid(
    columns: (1fr, 1fr, 1fr), column-gutter: 6pt,
    fill: theme-grad.card-bg-grad, inset: 6pt,
    stroke: (x, ..) => (top: theme.stroke-accent + (theme.brand-blue, theme.brand-accent, theme.brand-midnight).at(x), rest: theme.stroke-border + theme.box-border),
    stat-card(theme, [{{{n_statewide_od_deaths}}}], [Count of resident drug overdose deaths, {{{strip_period}}}]),
    stat-card(theme, [{{{statewide_od_rate}}}], [Statewide crude death rate, per 100,000 residents], color: theme.brand-accent),
    stat-card(theme, [{{{n_high_svi_counties}}}], [Counties in the top third for Social Vulnerability], color: theme.brand-midnight),
  )
]

// ============================================================
// HEADLINE MAP: SVI vs. OVERDOSE DEATH RATE
// ============================================================
#v(theme.space-md)
= SOCIAL VULNERABILITY AND OVERDOSE DEATH RATES, BY COUNTY
#v(theme.space-sm)

// Front-page real estate: the headline map is this page's dominant
// visual, so it gets most of the column width (80%) rather than an even
// split with the explainer text -- a narrow map rendered small would
// waste most of the page's vertical space below it (confirmed directly:
// an even 58/42 split left roughly two-thirds of the page blank beneath
// a map rendered too small to use the available height).
// The headline map's height was previously driven entirely by the
// source image's own aspect ratio (width: 100%, no height set) -- fine
// for the wide, short aspect ratio a real Kentucky county map happens to
// have, but silently at the mercy of whatever proportions a DIFFERENT
// jurisdiction's map export has. A more square map (this template's own
// test fixture is a 4:3 placeholder, not the elongated real thing) grows
// tall enough to push this page's remaining content onto an unwanted
// third page with no error or warning -- confirmed directly, not
// hypothetical: that's exactly what the 4:3 test fixture does. Capping
// the map at a fixed height and letting `fit: "contain"` letterbox
// (rather than crop or distort) any aspect ratio makes this page's total
// height deterministic regardless of the calling project's own map
// export shape. Tune headline-map-height if a future template revision
// needs the front page's vertical budget to shift.
//
// Reduced from 280pt: adding the bordered-table framing to WHAT SVI
// MEASURES (outer box + between-row rules) cost more vertical space
// than the section's original un-bordered layout, even after tightening
// that table's own spacing to a minimum -- confirmed directly by this
// template's own regression tests (test-county-choropleth.R), which
// failed at 280pt (3 pages, both the default fixture and the deliberate
// extreme-aspect-ratio stress test) and pass at 250pt. `fit: "contain"`
// means a smaller cap is still fully safe for any map aspect ratio, not
// just Kentucky's -- it can only letterbox more, never crop or distort.
//
// Re-verified after widening the map column to 80fr and bumping the SVI
// chip font to 7.5pt: a real compile sweep of this file's combined state
// at that point found the overflow cliff at 273pt (3 pages) vs. 272pt (2
// pages), a comfortable 22pt margin below 250pt.
//
// Re-verified AGAIN after a KIPRC editor's copyedit pass (spelling out
// CDC/ATSDR/NCHS and other prose lengthening across this page) plus
// bumping the shared page-footer() logo height from 24pt to 32pt: the
// cliff moved down to 265pt (3 pages) vs. 264pt (2 pages), 14pt margin.
//
// Re-verified a THIRD time after a bigger structural change: the footer
// is no longer wired via `set page(footer:)` at all (see
// apply-base-styles()'s comment in components.typ -- that mechanism
// unconditionally excludes its content from the PDF's accessibility
// tree, confirmed directly). It's now real, tagged content, self-placed
// per page via `#place(bottom + center, float: true)[#footer]` below and
// after the #pagebreak(). `float: true` matters: without it, the placed
// footer overlaid and silently hid whatever body content (this page's
// own footnote) happened to render at the same position -- confirmed
// directly by rendering to PNG and finding the footnote text missing,
// not by reasoning about it. WITH float: true, Typst reserves real
// space for the footer in the page's content flow instead of overlaying
// it, which means the footer now competes for the SAME vertical budget
// this page's other content does -- unlike before, when `page(footer:)`
// content was free (rendered in the page's dedicated footer region, not
// counted against this budget at all). apply-base-styles()'s
// margin-bottom is also cut from its 0.85in default to 0.056in (4pt)
// here specifically because that default reserved room for the OLD
// page(footer:) mechanism this template no longer uses -- keeping it
// would have double-spent vertical budget (reserved margin AND a
// floated footer both eating into the same space). Net result, swept
// fresh at this file's current combined state: the cliff is now 255pt
// (3 pages) vs. 254pt (2 pages) -- 250pt has a real but thin 4pt margin,
// tighter than any previous measurement in this file's history. Every
// number above this line is now historical context, not current fact --
// this is the one that's actually true right now. Re-sweep directly
// (same method as test-county-choropleth.R's page-count tests) after
// ANY future change near this page OR to the shared footer/margin
// mechanics -- do not trust any number in this comment, including this
// one, without re-verifying it first.
#let headline-map-height = 250pt
#grid(columns: (80fr, 20fr), column-gutter: 12pt,
  [
    #figure(
      box(stroke: 1pt + black, width: 100%, height: headline-map-height)[
        #align(center + horizon)[#image("{{{map0_path}}}", height: 100%, fit: "contain")]
      ],
      alt: "Kentucky county map, with each county labeled by name. Each county is shaded by a 3-by-3 bivariate color grid combining its overall Social Vulnerability Index tertile with its crude drug overdose death rate tertile. Dark green marks counties in the highest tertile for both measures; light gray marks counties in the lowest tertile for both.",
    )
  ],
  [
    #text-box(theme, theme-grad, [HOW TO READ THIS MAP], height: headline-map-height)[
      Each county is shaded by two ranks at once: Social Vulnerability Index (SVI, left #sym.arrow.r right) and overdose death rate (bottom #sym.arrow.r top), each split into thirds across all 120 counties.
      #v(theme.space-xs)
      // Verified directly against biscale::bi_pal("BlueOr", dim=3), not
      // eyeballed: bi_class 3-1 (x=SVI high, y=death rate low) = orange
      // #dd6a29; bi_class 1-3 (x=SVI low, y=death rate high) = blue
      // #169dd0. An earlier version of this callout had these swapped.
      *Dark green* #sym.dash.en top third on #emph[both]. *Orange* #sym.dash.en high SVI, lower death rate. *Blue* #sym.dash.en high death rate, lower SVI. *Light gray* #sym.dash.en low on both.
      #v(theme.space-xs)
      The color coding indicates where the two measures co-occur geographically -- not that one causes the other.
    ]
  ]
)

#v(theme.space-xs)
// map0_caption is a token, not hardcoded prose, for the same reason
// map1_caption..map4_caption (below) are: this is the analyst's actual
// regional finding from reading this specific map (e.g. an
// Appalachian-clustering pattern with a specific count of exceptions),
// true of this dataset, not a generic fact about what SVI is -- that
// generic explanation lives in the UNDERSTANDING THIS ANALYSIS narrative
// just below instead, so this caption isn't redundant with it.
#text(size: 8.5pt, fill: theme.text-secondary)[*Social Vulnerability Index (SVI).* {{{map0_caption}}}]

#v(theme.space-md)
= UNDERSTANDING THIS ANALYSIS
#v(theme.space-sm)
#text(size: 8.5pt)[Elevated drug overdose fatality rates do not occur in isolation; they are concentrated in communities where social and economic conditions create compounded risk. The SVI, developed by the Centers for Disease Control and Prevention, draws on census data to quantify four dimensions of community vulnerability: socioeconomic status, household characteristics, racial and ethnic minority status, and housing type and transportation. Higher SVI scores indicate communities with greater vulnerability.]

#v(theme.space-sm)
#text(size: 8.5pt)[The maps in this series use a bivariate choropleth design to display two variables at once: drug overdose death rate and social vulnerability. Dark green indicates counties high on both measures; orange or blue indicates counties high on one measure but low on the other; gray indicates counties low on both. This approach reveals not just where overdose burden is concentrated, but whether and how that concentration aligns with social vulnerability.]

#v(theme.space-sm)
#text(size: 8.5pt)[Each of the individual maps, on this page and on the reverse, examines a different vulnerability indicator -- the composite SVI and four individual component measures -- to show how the geographic relationship between overdose burden and social disadvantage shifts across measures.]

#v(theme.space-md)
= WHAT SVI MEASURES
#v(theme.space-xs)
#text(size: 7.5pt, fill: theme.text-secondary)[The SVI composite score combines county rankings across four CDC-defined themes, each based on multiple Census variables.]
#v(theme.space-xs)

// A compact row layout, not CDC's own tall-left-bar diagram (see
// https://www.atsdr.cdc.gov/place-health/php/svi/index.html) -- that
// shape is taller than it is wide and doesn't fit the space available
// here. A monochromatic blue ramp derived from theme.brand-blue, not
// CDC's own green/orange/purple/blue scheme: this page's bivariate
// legend already uses orange and green for a completely different
// meaning (SVI-vs-death-rate quadrants), and reusing those colors here
// for an unrelated 4-way category would read as if they were connected.
// This whole section is hardcoded (not tokenized) since it describes
// CDC's official SVI theme structure -- true for any dataset built on
// this template, not specific to one state's analysis.
#let svi-chip(label) = box(
  fill: white, stroke: 0.5pt + theme.border-color, radius: 2pt,
  outset: (y: 0.5pt), inset: (x: 4pt, y: 1pt),
)[#text(size: 7.5pt, fill: theme.text-secondary)[#label]]

// text-color is an explicit per-row argument, not automatic -- a
// monochromatic ramp needs a DIFFERENT label-text color once the
// background gets light enough that white text stops passing WCAG's
// 4.5:1 (small-text) requirement, exactly the "brand-accent vs
// brand-accent-text" split this package's own theme files already use
// for the identical reason. This was originally shipped with white
// text on all four rows, unverified -- confirmed wrong by a real PAC
// run against a consuming project (11 contrast errors), not caught in
// advance. Each pairing below is now verified with the actual WCAG
// contrast formula (not eyeballed): lighten 0%/20% + white text both
// clear 6:1; lighten 50%/70% + brand-midnight text clear 5.6:1 and
// 9:1. The gap between ~28%-38% lighten has NO safe text color (white
// and brand-midnight both fail there) -- confirmed by scanning the
// full 0-70% range, not assumed -- so the four stops deliberately skip
// past it rather than landing inside it. Also confirmed against a real
// compiled PDF (not just the R-side contrast formula): searched the
// rendered output for each predicted hex value and found matching
// pixels for all four, confirming Typst's real color.lighten() matches
// the linear-RGB-mix model these numbers were computed from.
#let svi-theme-label(color, label, text-color: white) = rect(
  fill: color, radius: 3pt, inset: (x: 6pt, y: 3pt), width: 100%,
)[#text(size: 7pt, weight: "bold", fill: text-color)[#label]]

#let svi-theme-items(items) = items.map(svi-chip).join(h(3pt))

// One outer bordered box (the whole visualization framed as a table),
// with a rule between each row -- rather than 4 separately-stacked
// mini-grids with gaps, this is ONE grid with 4 rows, so a single
// `stroke` rule covers every row boundary consistently instead of
// hand-placing 3 separate divider lines. Spacing (outer inset,
// row-gutter, per-cell bottom inset) is intentionally tight -- a first,
// more generously-spaced version pushed a consuming project's report
// onto an unwanted third page; this is the value that held at 2 pages
// there after two rounds of tightening.
#box(stroke: 0.5pt + theme.border-color, radius: 3pt, inset: 4pt, width: 100%)[
  #grid(
    columns: (100pt, 1fr), column-gutter: 8pt, row-gutter: 2pt,
    align: (left + horizon, left + horizon),
    stroke: (_, y) => if y < 3 { (bottom: 0.5pt + theme.border-color) } else { none },
    inset: (bottom: 2pt),
    svi-theme-label(theme.brand-blue, [SOCIOECONOMIC STATUS]),
    svi-theme-items(([Below 150% poverty], [Unemployed], [Housing cost burden], [No high school diploma], [No health insurance])),
    svi-theme-label(theme.brand-blue.lighten(20%), [HOUSEHOLD CHARACTERISTICS]),
    svi-theme-items(([Aged 65+], [Aged 17 and younger], [Civilian with a disability], [Single-parent households], [Limited English proficiency])),
    svi-theme-label(theme.brand-blue.lighten(50%), [RACIAL AND ETHNIC MINORITY STATUS], text-color: theme.brand-midnight),
    svi-theme-items(([Hispanic or Latino], [Black], [Asian], [American Indian/Alaska Native], [Native Hawaiian/Pacific Islander], [Two or more races], [Other races])),
    svi-theme-label(theme.brand-blue.lighten(70%), [HOUSING TYPE AND TRANSPORTATION], text-color: theme.brand-midnight),
    svi-theme-items(([Multi-unit structures], [Mobile homes], [Crowding], [No vehicle access], [Group quarters])),
  )
]

#v(theme.space-sm)
// A bare "*" at the start of a #text[] body starts bold-emphasis markup
// and breaks the compile with "unclosed delimiter" -- same escaping
// class as contact-email's "\@" (this file's header comment) and
// disclaimer_text's "\$" -- needs the literal "\*" escape. Any future
// literal asterisk (a footnote marker, multiplication, etc.) anywhere in
// this package's templates needs the same treatment.
#text(size: 7pt, fill: theme.text-muted)[\*SVI is the Centers for Disease Control and Prevention and Agency for Toxic Substances and Disease Registry's (CDC/ATSDR's) composite Social Vulnerability Index (sum of all four theme rankings), {{{data_vintage}}}. Overdose deaths are Kentucky resident deaths with an underlying cause of death consistent with the standard CDC/National Center for Health Statistics (NCHS) drug-poisoning definition (ICD-10 codes X40#sym.dash.en 44, X60#sym.dash.en 64, X85, Y10#sym.dash.en 14), {{{strip_period}}}, crude rate per 100,000 residents (not age-adjusted).]

] // close page-1 body
#place(bottom + center, float: true)[#footer]
#pagebreak()
#pad(x: theme.content-pad-x)[
#v(theme.space-sm)

// ============================================================
// COMPONENT FACTORS (page 2)
// ============================================================
= COMPONENT FACTORS BEHIND THE SVI SCORE
#v(theme.space-xs)
#text(size: 7.5pt, fill: theme.text-secondary)[The composite SVI score above is built from many measures. The four maps below isolate individual components most directly tied to health-care access and economic strain, each paired with the same overdose death rate as the map above -- to help visualize which specific factors are driving a county's overall vulnerability.]
#v(theme.space-sm)

// map1_caption..map4_caption are tokens, NOT hardcoded template prose
// like the rest of this file's static explanatory text -- these
// describe actual regional findings from the underlying analysis (e.g.
// Appalachian-vs-non-Appalachian patterns, specific metro clustering),
// which are true of THIS dataset, not a generic fact about what
// unemployment/insurance/poverty/housing cost mean that would hold for
// any consuming project. A future state/dataset using this template
// needs its own captions, supplied the same way disclaimer_text is.

// Same fixed-height-plus-fit:"contain" treatment as the headline map
// above, and for the same reason: four maps stacked into two rows means
// this page's total height is twice as sensitive to the source images'
// own aspect ratio as the front page was. component-map-row-gutter is
// deliberately generous (not the bare minimum that avoids visual
// overlap) -- an earlier version of this grid used row-gutter: 8pt,
// which left the second row's map boxes visually cramped directly under
// the first row's captions.
#let component-map-height = 220pt
#let component-map-row-gutter = 20pt
#grid(columns: (1fr, 1fr), column-gutter: 10pt, row-gutter: component-map-row-gutter,
  [
    #figure(
      box(stroke: 1pt + black, width: 100%, height: component-map-height)[
        #align(center + horizon)[#image("{{{map1_path}}}", height: 100%, fit: "contain")]
      ],
      alt: "Kentucky county map, bivariate choropleth of unemployment rate against overdose death rate, using the same 3-by-3 color grid as the headline map.",
    )
    #text(size: 7.5pt, fill: theme.text-secondary)[*{{{map_title1}}}.* {{{map1_caption}}}]
  ],
  [
    #figure(
      box(stroke: 1pt + black, width: 100%, height: component-map-height)[
        #align(center + horizon)[#image("{{{map2_path}}}", height: 100%, fit: "contain")]
      ],
      alt: "Kentucky county map, bivariate choropleth of the percentage of the population without health insurance against overdose death rate, using the same 3-by-3 color grid as the headline map.",
    )
    #text(size: 7.5pt, fill: theme.text-secondary)[*{{{map_title2}}}.* {{{map2_caption}}}]
  ],
  [
    #figure(
      box(stroke: 1pt + black, width: 100%, height: component-map-height)[
        #align(center + horizon)[#image("{{{map3_path}}}", height: 100%, fit: "contain")]
      ],
      alt: "Kentucky county map, bivariate choropleth of the percentage of persons below 150 percent of the poverty line against overdose death rate, using the same 3-by-3 color grid as the headline map.",
    )
    #text(size: 7.5pt, fill: theme.text-secondary)[*{{{map_title3}}}.* {{{map3_caption}}}]
  ],
  [
    #figure(
      box(stroke: 1pt + black, width: 100%, height: component-map-height)[
        #align(center + horizon)[#image("{{{map4_path}}}", height: 100%, fit: "contain")]
      ],
      alt: "Kentucky county map, bivariate choropleth of the percentage of housing units that are cost-burdened against overdose death rate, using the same 3-by-3 color grid as the headline map.",
    )
    #text(size: 7.5pt, fill: theme.text-secondary)[*{{{map_title4}}}.* {{{map4_caption}}}]
  ],
)

#v(theme.space-sm)
#rect(fill: theme-grad.disclaimer-bg-grad, stroke: (left: theme.stroke-accent-left + theme.disclaimer-border, rest: theme.stroke-border + theme.box-border), radius: theme.radius-card, inset: 5pt, width: 100%)[
  // Same pattern used by every other onepagr template's DISCLAIMER box --
  // a locally-scoped `show heading: set text(...)` styling rule (not a
  // content-replacing rule) keeps `== DISCLAIMER` tagged as a real
  // heading in the PDF's structure tree rather than an ordinary paragraph
  // that merely looks bold. See components.typ's apply-base-styles
  // comment for why this distinction matters for PDF/UA conformance.
  #show heading: set text(size: 8pt, weight: "bold", fill: theme.disclaimer-text, tracking: 0.5pt)
  == DISCLAIMER
  #v(theme.space-xs)
  #text(size: 8pt, fill: theme.disclaimer-text)[{{{disclaimer_text}}}]
]

#v(theme.space-xs)
#text(size: 7pt, fill: theme.text-muted)[*Data sources:* {{{footnote_sources}}} #h(0.5em)|#h(0.5em) *Period:* {{{strip_period}}} #h(0.5em)|#h(0.5em) *Contact:* {{{org_full}}} at #link("mailto:" + contact-email)[#contact-email]]
] // close body #pad(x: theme.content-pad-x)
#place(bottom + center, float: true)[#footer]

] // close #apply-base-styles body
