// County Choropleth Series template -- whisker-tokenized Typst, rendered
// by onepagr::render_onepager(). All placeholder tokens map to named
// elements in the calling script's `data` list.
//
// SHAPE: unlike cohort_summary (contrasts two groups) or trend_snapshot
// (tracks one metric over time), this template's informational shape is a
// GEOGRAPHIC bivariate comparison -- one headline choropleth map (an
// outcome variable vs. a composite index) on the front, plus the
// composite index's individual component maps on the back, each with an
// interpretive caption. Generalized from the KY SVI x drug-overdose
// linkage analysis; the map images themselves (5 pre-rendered PNGs, one
// bivariate choropleth each, built with the biscale/ggplot2/cowplot R
// stack) are supplied by the calling script, not generated by Typst --
// this template only lays them out with real alt text and captions.
//
// THEME/COMPONENT ARCHITECTURE: same pattern as every other onepagr
// template -- theme.typ/components.typ are staged in next to this file at
// compile time by render_onepager()/export_template(), so nothing here
// needs to change to re-skin. See cohort_summary/template.typ's header
// comment for the full rationale (lexical-scoping bug this avoids).
#import "theme.typ": theme, theme-grad
#import "components.typ": *

// Route contact_email through a variable rather than splicing
// {{{contact_email}}} directly into markup body wherever it's displayed.
// Typst's markup parser treats a bare "@" as the start of label-reference
// syntax (e.g. "kiprc@uky.edu" parses as "kiprc" + a reference to label
// <uky.edu>, failing to compile with "label <uky.edu> does not exist") --
// confirmed directly, not assumed. Escaping it as "\@" only fixes that
// for a token substituted straight into markup SOURCE text; substituted
// into a quoted Typst STRING argument instead (as page-footer's own
// contact-email parameter is), "\@" is not a recognized string escape and
// the literal backslash character renders in the output. Interpolating a
// plain (unescaped) string value via #variable-name, as done below and in
// page-footer, sidesteps this entirely -- Typst never re-parses an
// already-evaluated string's characters for markup syntax, so the "@" is
// inert either way. Keep contact_email UNESCAPED in the R-side data.
#let contact-email = "{{{contact_email}}}"

// Logo paths/alt-text and the header texture are tokens, not hardcoded
// literals -- see cohort_summary/template.typ's identical comment for
// why. Also fixed here: the last argument now uses the contact-email
// variable (defined above) instead of the raw {{{contact_email}}} token
// directly -- consistent with why that variable exists at all (see this
// file's header comment on contact-email), even though passing the raw
// token here was never actually broken given this template's fixture
// already supplies an unescaped value.
#let footer = page-footer(
  theme, theme-grad,
  "{{{logo_partner_a_path}}}", "{{{logo_partner_a_alt}}}", "{{{show_partner_a}}}",
  "{{{logo_primary_path}}}", "{{{logo_primary_alt}}}",
  "{{{logo_partner_b_path}}}", "{{{logo_partner_b_alt}}}", "{{{show_partner_b}}}",
  "{{{org_full}}}", "{{{contact_url}}}", contact-email,
)

#apply-base-styles([{{{doc_title}}}], "{{{org_full}}}", theme, footer)[

// ============================================================
// HEADER
// ============================================================
#block(width: 100%, fill: theme-grad.brand-blue-grad, clip: true, inset: (x: 20pt, y: 10pt), above: 0pt, below: 0pt)[
  #place(top + right, dx: 40pt, dy: -30pt)[
    #pdf.artifact(kind: "background")[#image("{{{header_texture_path}}}", width: 260pt)]
  ]
  #grid(columns: (auto, 1fr), column-gutter: 14pt, align: horizon,
    image("{{{logo_primary_path}}}", height: 28pt, alt: "{{{logo_primary_alt}}}"),
    [
      #text(fill: white, size: 12pt, weight: "bold")[{{{doc_title}}}] \
      #text(fill: white.transparentize(15%), size: 9pt)[{{{doc_subtitle}}}]
    ]
  )
]
#block(fill: theme.brand-midnight, inset: (x: 20pt, y: 6pt), width: 100%, above: 0pt)[
  #text(fill: white, size: 8pt)[
    *DATA* {{{strip_data}}}  #h(1.5em)
    *PERIOD* {{{strip_period}}}  #h(1.5em)
    *DESIGN* {{{strip_design}}}  #h(1.5em)
    *GEOGRAPHY* {{{strip_geography}}}
  ]
]

#pad(x: theme.content-pad-x)[
#v(theme.space-md)

// ============================================================
// AT A GLANCE
// ============================================================
= {{{strip_geography}}} AT A GLANCE #sym.dash.en {{{strip_period}}}
#v(theme.space-sm)

#block(breakable: false)[
  #grid(
    columns: (1fr, 1fr, 1fr), column-gutter: 6pt,
    fill: theme-grad.card-bg-grad, inset: 6pt,
    stroke: (x, ..) => (top: theme.stroke-accent + (theme.brand-blue, theme.brand-accent, theme.brand-midnight).at(x), rest: theme.stroke-border + theme.box-border),
    stat-card(theme, [{{{n_statewide_od_deaths}}}], [Resident drug overdose deaths, {{{strip_period}}}]),
    stat-card(theme, [{{{statewide_od_rate}}}], [Statewide crude death rate, per 100,000 residents], color: theme.brand-accent),
    stat-card(theme, [{{{n_high_svi_counties}}}], [Counties in the highest Social Vulnerability Index tertile], color: theme.brand-midnight),
  )
]

// ============================================================
// HEADLINE MAP: SVI vs. OVERDOSE DEATH RATE
// ============================================================
#v(theme.space-md)
= SOCIAL VULNERABILITY AND OVERDOSE DEATH RATES, BY COUNTY
#v(theme.space-sm)

// Front-page real estate: the headline map is this page's dominant
// visual, so it gets most of the column width (75%) rather than an even
// split with the explainer text -- a narrow map rendered small would
// waste most of the page's vertical space below it (confirmed directly:
// an even 58/42 split left roughly two-thirds of the page blank beneath
// a map rendered too small to use the available height).
#grid(columns: (75fr, 25fr), column-gutter: 12pt,
  [
    #figure(
      box(stroke: 1pt + black, width: 100%)[#image("{{{map0_path}}}", width: 100%)],
      alt: "Kentucky county map, with each county labeled by name. Each county is shaded by a 3-by-3 bivariate color grid combining its overall Social Vulnerability Index tertile with its crude drug overdose death rate tertile. Dark green marks counties in the highest tertile for both measures; light gray marks counties in the lowest tertile for both.",
    )
  ],
  [
    #text-box(theme, theme-grad, [HOW TO READ THIS MAP])[
      Each county is shaded by two ranks at once: Social Vulnerability Index (SVI, left #sym.arrow.r right) and overdose death rate (bottom #sym.arrow.r top), each split into thirds across all 120 counties.
      #v(theme.space-xs)
      // Verified directly against biscale::bi_pal("BlueOr", dim=3), not
      // eyeballed: bi_class 3-1 (x=SVI high, y=death rate low) = orange
      // #dd6a29; bi_class 1-3 (x=SVI low, y=death rate high) = blue
      // #169dd0. An earlier version of this callout had these swapped.
      *Dark green* #sym.dash.en top third on #emph[both]. *Orange* #sym.dash.en high SVI, lower death rate. *Blue* #sym.dash.en high death rate, lower SVI. *Light gray* #sym.dash.en low on both.
      #v(theme.space-xs)
      Shows where the two measures co-occur geographically -- not that one causes the other.
    ]
  ]
)

#v(theme.space-xs)
// map0_caption is a token, not hardcoded prose, for the same reason
// map1_caption..map4_caption (below) are: this is the analyst's actual
// regional finding from reading this specific map (e.g. an
// Appalachian-clustering pattern with a specific count of exceptions),
// true of this dataset, not a generic fact about what SVI is -- that
// generic explanation lives in the UNDERSTANDING THIS ANALYSIS narrative
// just below instead, so this caption isn't redundant with it.
#text(size: 8.5pt, fill: theme.text-secondary)[*Social Vulnerability Index (SVI).* {{{map0_caption}}}]

#v(theme.space-md)
= UNDERSTANDING THIS ANALYSIS
#v(theme.space-sm)
#text(size: 8.5pt)[Drug overdose fatality does not occur in isolation; it concentrates in communities where social and economic conditions create compounding risk. The Social Vulnerability Index (SVI), developed by the CDC, draws on census data to quantify four dimensions of community vulnerability: socioeconomic status, household characteristics, racial and ethnic minority status, and housing type and transportation. Higher SVI scores indicate communities with greater risk.]

#v(theme.space-sm)
#text(size: 8.5pt)[The maps in this series use a bivariate choropleth design to display two variables at once: fatal drug overdose death rate and social vulnerability. Dark green indicates counties high on both measures; orange or blue indicates counties high on one measure but low on the other; gray indicates counties low on both. This approach reveals not just where overdose burden is concentrated, but whether and how that concentration aligns with social vulnerability.]

#v(theme.space-sm)
#text(size: 8.5pt)[Each of the five maps examines a different vulnerability indicator -- the composite SVI and four component measures -- to show how the geographic relationship between overdose burden and social disadvantage shifts across measures.]

#v(theme.space-md)
= WHAT SVI MEASURES
#v(theme.space-xs)
#text(size: 7.5pt, fill: theme.text-secondary)[SVI's composite score sums county rankings across four CDC-defined themes, each built from several Census variables:]
#v(theme.space-xs)

// A compact row layout, not CDC's own tall-left-bar diagram (see
// https://www.atsdr.cdc.gov/place-health/php/svi/index.html) -- that
// shape is taller than it is wide and doesn't fit the space available
// here. A monochromatic blue ramp derived from theme.brand-blue, not
// CDC's own green/orange/purple/blue scheme: this page's bivariate
// legend already uses orange and green for a completely different
// meaning (SVI-vs-death-rate quadrants), and reusing those colors here
// for an unrelated 4-way category would read as if they were connected.
// This whole section is hardcoded (not tokenized) since it describes
// CDC's official SVI theme structure -- true for any dataset built on
// this template, not specific to one state's analysis.
#let svi-chip(label) = box(
  fill: white, stroke: 0.5pt + theme.border-color, radius: 2pt,
  outset: (y: 1pt), inset: (x: 4pt, y: 1.5pt),
)[#text(size: 6.3pt, fill: theme.text-secondary)[#label]]

#let svi-theme-row(color, label, items) = grid(
  columns: (100pt, 1fr), column-gutter: 8pt, align: (left + horizon, left + horizon),
  rect(fill: color, radius: 3pt, inset: (x: 6pt, y: 4pt), width: 100%)[#text(size: 7pt, weight: "bold", fill: white)[#label]],
  items.map(svi-chip).join(h(3pt)),
)

#stack(spacing: 4pt,
  svi-theme-row(theme.brand-blue, [SOCIOECONOMIC STATUS], ([Below 150% poverty], [Unemployed], [Housing cost burden], [No high school diploma], [No health insurance])),
  svi-theme-row(theme.brand-blue.lighten(25%), [HOUSEHOLD CHARACTERISTICS], ([Aged 65+], [Aged 17 and younger], [Civilian with a disability], [Single-parent households], [Limited English proficiency])),
  svi-theme-row(theme.brand-blue.lighten(45%), [RACIAL AND ETHNIC MINORITY STATUS], ([Hispanic or Latino], [Black], [Asian], [American Indian/Alaska Native], [Native Hawaiian/Pacific Islander], [Two or more races], [Other races])),
  svi-theme-row(theme.brand-blue.lighten(60%), [HOUSING TYPE AND TRANSPORTATION], ([Multi-unit structures], [Mobile homes], [Crowding], [No vehicle access], [Group quarters])),
)

#v(theme.space-sm)
#text(size: 7pt, fill: theme.text-muted)[SVI is CDC/ATSDR's composite Social Vulnerability Index (sum of all four theme rankings), {{{data_vintage}}}. Overdose deaths are Kentucky resident deaths with an underlying cause of death consistent with the standard CDC/NCHS drug-poisoning definition (ICD-10 X40#sym.dash.en 44, X60#sym.dash.en 64, X85, Y10#sym.dash.en 14), {{{strip_period}}}, crude rate per 100,000 residents (not age-adjusted).]

] // close page-1 body
#pagebreak()
#pad(x: theme.content-pad-x)[
#v(theme.space-sm)

// ============================================================
// COMPONENT FACTORS (page 2)
// ============================================================
= COMPONENT FACTORS BEHIND THE SVI SCORE
#v(theme.space-xs)
#text(size: 7.5pt, fill: theme.text-secondary)[The composite SVI score above is built from many measures. The four maps below isolate individual components most directly tied to health-care access and economic strain, each paired with the same overdose death rate as the headline map -- so a reader can see which specific factor is driving a county's vulnerability, not just that it's vulnerable overall.]
#v(theme.space-sm)

// map1_caption..map4_caption are tokens, NOT hardcoded template prose
// like the rest of this file's static explanatory text -- these
// describe actual regional findings from the underlying analysis (e.g.
// Appalachian-vs-non-Appalachian patterns, specific metro clustering),
// which are true of THIS dataset, not a generic fact about what
// unemployment/insurance/poverty/housing cost mean that would hold for
// any consuming project. A future state/dataset using this template
// needs its own captions, supplied the same way disclaimer_text is.

#grid(columns: (1fr, 1fr), column-gutter: 10pt, row-gutter: 8pt,
  [
    #figure(
      box(stroke: 1pt + black, width: 100%)[#image("{{{map1_path}}}", width: 100%)],
      alt: "Kentucky county map, bivariate choropleth of unemployment rate against overdose death rate, using the same 3-by-3 color grid as the headline map.",
    )
    #text(size: 7.5pt, fill: theme.text-secondary)[*{{{map_title1}}}.* {{{map1_caption}}}]
  ],
  [
    #figure(
      box(stroke: 1pt + black, width: 100%)[#image("{{{map2_path}}}", width: 100%)],
      alt: "Kentucky county map, bivariate choropleth of the percentage of the population without health insurance against overdose death rate, using the same 3-by-3 color grid as the headline map.",
    )
    #text(size: 7.5pt, fill: theme.text-secondary)[*{{{map_title2}}}.* {{{map2_caption}}}]
  ],
  [
    #figure(
      box(stroke: 1pt + black, width: 100%)[#image("{{{map3_path}}}", width: 100%)],
      alt: "Kentucky county map, bivariate choropleth of the percentage of persons below 150 percent of the poverty line against overdose death rate, using the same 3-by-3 color grid as the headline map.",
    )
    #text(size: 7.5pt, fill: theme.text-secondary)[*{{{map_title3}}}.* {{{map3_caption}}}]
  ],
  [
    #figure(
      box(stroke: 1pt + black, width: 100%)[#image("{{{map4_path}}}", width: 100%)],
      alt: "Kentucky county map, bivariate choropleth of the percentage of housing units that are cost-burdened against overdose death rate, using the same 3-by-3 color grid as the headline map.",
    )
    #text(size: 7.5pt, fill: theme.text-secondary)[*{{{map_title4}}}.* {{{map4_caption}}}]
  ],
)

#v(theme.space-sm)
#rect(fill: theme-grad.disclaimer-bg-grad, stroke: (left: theme.stroke-accent-left + theme.disclaimer-border, rest: theme.stroke-border + theme.box-border), radius: theme.radius-card, inset: 5pt, width: 100%)[
  // Same pattern used by every other onepagr template's DISCLAIMER box --
  // a locally-scoped `show heading: set text(...)` styling rule (not a
  // content-replacing rule) keeps `== DISCLAIMER` tagged as a real
  // heading in the PDF's structure tree rather than an ordinary paragraph
  // that merely looks bold. See components.typ's apply-base-styles
  // comment for why this distinction matters for PDF/UA conformance.
  #show heading: set text(size: 8pt, weight: "bold", fill: theme.disclaimer-text, tracking: 0.5pt)
  == DISCLAIMER
  #v(theme.space-xs)
  #text(size: 8pt, fill: theme.disclaimer-text)[{{{disclaimer_text}}}]
]

#v(theme.space-xs)
#text(size: 7pt, fill: theme.text-muted)[*Data sources:* {{{footnote_sources}}} #h(0.5em)|#h(0.5em) *Period:* {{{strip_period}}} #h(0.5em)|#h(0.5em) *Contact:* {{{org_full}}} at #link("mailto:" + contact-email)[#contact-email]]
] // close body #pad(x: theme.content-pad-x)

] // close #apply-base-styles body
